# Generated by Django 4.1.7 on 2023-03-17 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='patient',
        ),
    ]
