# Generated by Django 4.1.7 on 2023-03-17 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_profile_delete_patient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='aadhar',
            new_name='aadhaar',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='fname',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='patient_id',
            new_name='patientID',
        ),
    ]
